Feature socialsignup
Yalday/FinalYaldayGateway pull request #1
Opened 2017-01-28 18:08 UTC by martinrae123

Created pull request for review and merge with master

2017-01-28 19:44 UTC, abetterway2feel commented on README.md
> -
this puts the travis badge on the github page. Please put it back in

2017-01-28 19:56 UTC, abetterway2feel requested changes
Need to revert the readme change otherwise, the Travis badge will disappear. Other than that i guess a lot of it was generated?

2017-01-28 19:56 UTC, abetterway2feel commented on src/main/java/com/yalday/gateway/config/CacheConfiguration.java
> +        });
nice that it's using the Streams library now

2017-01-28 19:56 UTC, abetterway2feel commented on src/main/java/com/yalday/gateway/domain/SocialUserConnection.java
> +@Table(name = "jhi_social_user_connection")
we really have a table with jhi_ prefix?

2017-01-28 19:56 UTC, abetterway2feel commented on src/main/java/com/yalday/gateway/repository/UserRepository.java
> -    Optional<User> findOneById(Long userId);
we dont need to find by id?

2017-01-28 19:56 UTC, abetterway2feel commented on src/main/java/com/yalday/gateway/security/social/CustomSignInAdapter.java
> +    @SuppressWarnings("unused")
why the supression? don't we use the log?

2017-01-28 19:56 UTC, abetterway2feel commented on src/main/java/com/yalday/gateway/service/UserService.java
> +            .findOne(id))
prefer the old naming imo

2017-01-29 16:12 UTC, abetterway2feel commented on .travis.yml
> -  slack: yalday:xP5IlHDXIkyu5jIEvjzHKG2x
this will need to be reinstated too

2017-01-29 16:28 UTC, abetterway2feel commented on src/test/javascript/spec/app/components/Social Login/social-auth.controller.spec.js
> +                    //new shit
come on!

2017-01-30 18:52 UTC, martinrae123 commented on .travis.yml
> -  slack: yalday:xP5IlHDXIkyu5jIEvjzHKG2x
Done

2017-01-30 18:52 UTC, martinrae123 commented on README.md
> -
Done

2017-01-30 18:52 UTC, merged