Merch signup gw
Yalday/FinalYaldayGateway pull request #2
Opened 2017-03-25 12:51 UTC by martinrae

This is the changes for Merch signup on Gateway including the new call to the Merchant Service

2017-03-25 13:14 UTC, abetterway2feel commented
whstsvis the revase commit? Rebasing should eliminate the need for an extra commit (I.e. With git push -f)

2017-03-25 22:02 UTC, abetterway2feel requested changes
Ok, decided to stop being lazy and gave it a look. I am still a little rusty with javascript and angular but hey. On the whole, it looks fine to me.

I do think the tests are a little light still, but I could be easily disproven by some coverage stats. This I think we can improve on regardless. 

A few minor things I would change. eg. comments. (FYI - commented code = the devil imo.)

Also just a little explanation around naming clear vs maybe close or maybe I'm misunderstanding what that thing does.

2017-03-25 22:02 UTC, abetterway2feel commented on src/main/webapp/app/entities/merchant/merchant-delete-dialog.controller.js
> +        function clear () {
why not close - since that's what this actually does?

2017-03-25 22:02 UTC, abetterway2feel commented on src/main/webapp/app/entities/merchant/merchant-delete-dialog.html
> +                ng-click="vm.clear()">&times;</button>
ie.e would now be vm.close()

2017-03-25 22:02 UTC, abetterway2feel commented on src/main/webapp/app/entities/merchant/merchant-signup.html
> +        </div-->
please delete commented code

2017-03-25 22:02 UTC, abetterway2feel commented on src/test/javascript/e2e/entities/merchant.js
> +        element(by.css('button[type=submit]')).click();
guess the above steps get performed in many tests. we should probably move them to a some sort of MockLogin object... not in the PR but...at somepoint

2017-03-25 22:02 UTC, abetterway2feel commented on src/test/javascript/spec/app/entities/merchant/merchant-dialog.controller.spec.js
> +/*'use strict';
commented test?

2017-03-25 22:02 UTC, abetterway2feel commented on src/test/javascript/spec/app/entities/merchant/merchant-signup.controller.spec.js
> +      //Constructor is  MerchantDialogController ($timeout, $scope, $stateParams, $uibModalInstance, entity, Merchant)
comment?

2017-03-25 22:02 UTC, abetterway2feel commented on src/test/javascript/spec/app/entities/merchant/merchant-signup.controller.spec.js
> +      it('test1', function() {
test1? something more descriptive would be nicer

2017-03-25 22:06 UTC, abetterway2feel commented
webhook test

2017-03-25 22:12 UTC, abetterway2feel commented
another webhook test

2017-03-28 19:41 UTC, martinrae commented on src/main/webapp/app/entities/merchant/merchant-delete-dialog.controller.js
> +        function clear () {
i think this is because its a reserved word in javascript

2017-03-28 19:41 UTC, martinrae commented on src/main/webapp/app/entities/merchant/merchant-delete-dialog.html
> +                ng-click="vm.clear()">&times;</button>
same as above

2017-03-28 19:47 UTC, abetterway2feel commented on src/main/webapp/app/entities/merchant/merchant-delete-dialog.controller.js
> +        function clear () {
nice. i did not realize that. That really sucks in javascript

2017-03-28 19:49 UTC, chriskiernan87 commented on src/main/webapp/app/entities/merchant/merchant-dialog.controller.js
> +                 console.log(vm.merchant);
console.log statement left in code. Fine to use this for debugging but not something we should leave lying around.

2017-03-28 19:49 UTC, chriskiernan87 commented on src/main/webapp/app/entities/merchant/merchant-signup.html
> +        <!--div class="form-group">
Commented code. Not the end of the world but if we aren't using it then we should remove it.

2017-03-28 19:49 UTC, chriskiernan87 commented on src/main/webapp/app/home/home.html
> +                   If you want to <a class="alert-link" href="" ng-click="vm.login()">sign in</a>, you can try the default accounts:<br/>- Administrator (login="admin" and password="admin") <br/>- Us
What's the purpose of this code?

2017-03-28 19:49 UTC, chriskiernan87 commented on src/test/javascript/e2e/entities/merchant.js
> +                expect(value).toMatch(/yaldayGatewayApp.merchant.home.title/);
Is this actually asserting that we've loaded any merchants or is it just asserting that we've moved to the page where we would expect merchants to be?

2017-03-28 19:49 UTC, chriskiernan87 commented on src/test/javascript/spec/app/entities/merchant/merchant-signup.controller.spec.js
> +
What's the deal with the test names?

2017-03-28 20:08 UTC, martinrae commented on src/main/webapp/app/entities/merchant/merchant-delete-dialog.controller.js
> +        function clear () {
Yep seems like they have a ton of them when i googled it

2017-03-28 20:17 UTC, martinrae commented on src/main/webapp/app/home/home.html
> +                   If you want to <a class="alert-link" href="" ng-click="vm.login()">sign in</a>, you can try the default accounts:<br/>- Administrator (login="admin" and password="admin") <br/>- Us
This code simply tells the user that they are logged in as ******* OR alternately provides a login link to users who are new or have not logged in

2017-03-28 20:18 UTC, martinrae commented on src/test/javascript/e2e/entities/merchant.js
> +        element(by.css('button[type=submit]')).click();
agreed

2017-03-28 20:22 UTC, martinrae commented on src/main/webapp/app/home/home.html
> +                   If you want to <a class="alert-link" href="" ng-click="vm.login()">sign in</a>, you can try the default accounts:<br/>- Administrator (login="admin" and password="admin") <br/>- Us
This simply tells users who they are logged in as ******** OR alternately asks them to log in / sign up

2017-03-28 20:55 UTC, martinrae commented on src/main/webapp/app/home/home.html
> +                   If you want to <a class="alert-link" href="" ng-click="vm.login()">sign in</a>, you can try the default accounts:<br/>- Administrator (login="admin" and password="admin") <br/>- Us
This is simply to ask users who have not logged in to log in or sign up

2017-03-28 20:55 UTC, martinrae commented on src/test/javascript/e2e/entities/merchant.js
> +                expect(value).toMatch(/yaldayGatewayApp.merchant.home.title/);
This is more auto generated JHipster Bliss :)
I believe that this asserts that the value is now the merchants page only i.e. does not load any merchants

2017-03-28 20:55 UTC, martinrae commented on src/test/javascript/spec/app/entities/merchant/merchant-signup.controller.spec.js
> +
For once not my dodgy handywork :)

2017-03-28 20:55 UTC, martinrae commented on src/main/webapp/app/entities/merchant/merchant-signup.html
> +        <!--div class="form-group">
Removed

2017-03-28 20:58 UTC, martinrae commented on src/test/javascript/spec/app/entities/merchant/merchant-dialog.controller.spec.js
> +/*'use strict';
Deleted

2017-03-28 20:58 UTC, martinrae commented on src/test/javascript/spec/app/entities/merchant/merchant-signup.controller.spec.js
> +      //Constructor is  MerchantDialogController ($timeout, $scope, $stateParams, $uibModalInstance, entity, Merchant)
Removed

2017-03-28 21:15 UTC, abetterway2feel commented on src/test/javascript/spec/app/entities/merchant/merchant-signup.controller.spec.js
> +
who's is it? generated? Asif? to be honest would like the names to be descriptive and enumerated tests are far from that

2017-03-28 21:15 UTC, abetterway2feel commented on src/test/javascript/spec/app/entities/merchant/merchant-dialog.controller.spec.js
> +/*'use strict';
if thats the case why is it still here?

2017-03-29 17:59 UTC, merged